### ISSUE TITLE
No Feedback From Game on Loose

### ISSUE THREAD

**Issue by GoodyCarlo** [naixsu/Osu-Thingy#10]
When the player looses there is no feedback from the game

Intended behavior:
- Return to menu
- Loose splash screen offering restart or go to main menu

**Comment by naixsu** [comment]
Hi @GoodyCarlo,

Thank you for bringing this issue to my attention. I'm pleased to inform you that the problem has been resolved in the latest release, [version 1.1.0 beta](https://github.com/naixsu/Osu-Thingy/releases/tag/v1.1.0-beta). I appreciate your patience and encourage you to update to the latest version to enjoy the fix.

If you encounter any further issues or have additional feedback, please don't hesitate to let me know.

Best regards,
your mom
